# docker-compose example for elysia app
version: '1'
services:
  elysia:
    image: ./Dockerfile
    container_name: elysia
    restart: always
    ports:
      - 80:3000
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}