name: auto-deploy
run-name: ${{ github.actor }} is deploying
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH key
      run: |
        sudo ufw allow ssh
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        sudo chmod 400 ~/.ssh/id_rsa
        ls -la ~/.ssh
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        sudo chmod 644 ~/.ssh/known_hosts
    
    - name: Deploy with SSH
      run: |
        ssh -vvv -i ~/.ssh/id_rsa ubuntu@ec2-35-180-208-136.eu-west-3.compute.amazonaws.com "cd /home/bethapp; sudo git pull; pm2 restart 0"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}